# Generated by scripts/plugins.ts.
input=$(cat 2>/dev/null | tr -d '\n')
field() { printf '%s' "$input" | sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p"; }
session=$(field session_id | tr -cd 'A-Za-z0-9_-')
[ -n "$session" ] || session=unknown
dir=$(field cwd)
[ -d "$dir" ] || dir=$PWD
state="${TMPDIR:-/tmp}/layermap-claude"
mkdir -p "$state" 2>/dev/null
code_changes() {
  git -C "$dir" rev-parse --verify --quiet HEAD >/dev/null 2>&1 || return 0
  git -C "$dir" diff HEAD --no-ext-diff --no-color -- '*.ts' '*.tsx' '*.mts' '*.cts' '*.js' '*.jsx' '*.mjs' '*.cjs' '*.go' '*.py' '*.java' 2>/dev/null
  git -C "$dir" ls-files --others --exclude-standard -- '*.ts' '*.tsx' '*.mts' '*.cts' '*.js' '*.jsx' '*.mjs' '*.cjs' '*.go' '*.py' '*.java' 2>/dev/null |
    while IFS= read -r file; do printf '%s %s\n' "$file" "$(git -C "$dir" hash-object -- "$file" 2>/dev/null)"; done
}
changes=$(code_changes)
fingerprint=$(printf '%s' "$changes" | git hash-object --stdin 2>/dev/null)
printf '%s' "$fingerprint" > "$state/$session.start" 2>/dev/null
cat <<'EOF'
{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"The layermap MCP server is available here. For questions about what calls a function, what a change affects or where code is used, start with its project_explore_map tool (direction INCOMING, depth up to 8) before grep, then confirm in source. After editing code, call its project_check_changes tool before reporting the work done."}}
EOF
