# Generated by scripts/plugins.ts.
[ "${LAYERMAP_STOP_CHECK:-1}" = 0 ] && exit 0
input=$(cat 2>/dev/null | tr -d '\n')
field() { printf '%s' "$input" | sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p"; }
session=$(field session_id | tr -cd 'A-Za-z0-9_-')
[ -n "$session" ] || session=unknown
dir=$(field cwd)
[ -d "$dir" ] || dir=$PWD
state="${TMPDIR:-/tmp}/layermap-claude"
mkdir -p "$state" 2>/dev/null
code_changes() {
  git -C "$dir" rev-parse --verify --quiet HEAD >/dev/null 2>&1 || return 0
  git -C "$dir" diff HEAD --no-ext-diff --no-color -- '*.ts' '*.tsx' '*.mts' '*.cts' '*.js' '*.jsx' '*.mjs' '*.cjs' '*.go' '*.py' '*.java' 2>/dev/null
  git -C "$dir" ls-files --others --exclude-standard -- '*.ts' '*.tsx' '*.mts' '*.cts' '*.js' '*.jsx' '*.mjs' '*.cjs' '*.go' '*.py' '*.java' 2>/dev/null |
    while IFS= read -r file; do printf '%s %s\n' "$file" "$(git -C "$dir" hash-object -- "$file" 2>/dev/null)"; done
}
changes=$(code_changes)
fingerprint=$(printf '%s' "$changes" | git hash-object --stdin 2>/dev/null)
case "$input" in *'"stop_hook_active":true'* | *'"stop_hook_active": true'*) exit 0 ;; esac
[ -n "$changes" ] || exit 0
[ "$fingerprint" = "$(cat "$state/$session.start" 2>/dev/null)" ] && exit 0
[ "$fingerprint" = "$(cat "$state/$session.checked" 2>/dev/null)" ] && exit 0
printf '%s' "$fingerprint" > "$state/$session.checked" 2>/dev/null
transcript=$(field transcript_path)
if [ -f "$transcript" ]; then
  edited=$(grep -nE '"name": *"(Edit|Write|MultiEdit|NotebookEdit)"' "$transcript" 2>/dev/null | tail -n 1 | cut -d: -f1)
  checked=$(grep -nE '"name": *"[^"]*project_check_changes"' "$transcript" 2>/dev/null | tail -n 1 | cut -d: -f1)
  [ -n "$checked" ] && [ "$checked" -gt "${edited:-0}" ] && exit 0
fi
cat <<'EOF'
{"decision":"block","reason":"Code changed in this session. Before finishing, call the LayerMap tool project_check_changes: it lists the routes, jobs and commands the changes reach and the existing tests related to them. Check the affected entry points in source, and run the related tests if the change needs verifying. If you already checked these changes, say so briefly and finish."}
EOF
