// Generated by scripts/plugins.ts.
import { spawn } from "node:child_process";

const args = ["-y", "layermap@0.1.15", "mcp"];
const server =
  process.platform === "win32"
    ? spawn(`npx ${args.join(" ")}`, { stdio: "inherit", shell: true, windowsHide: true })
    : spawn("npx", args, { stdio: "inherit" });
for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) process.on(signal, () => server.kill(signal));
server.on("error", (error) => {
  process.stderr.write(`layermap: could not start npx: ${error.message}\n`);
  process.exit(1);
});
server.on("exit", (code) => process.exit(code ?? 1));
