// Writes the Claude Code and Codex plugins and their marketplace entries. The published plugins
// start the server with npx from npm; --dev writes the same plugins, started from this checkout,
// into another directory for trying them before a release.
//
// usage: node --import tsx scripts/plugins.ts [--dev <directory>]
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { AGENT_MAP_NOTE } from "../src/agent/tools";

const packageRoot = fileURLToPath(new URL("../", import.meta.url));
const REPOSITORY = "https://github.com/coffeecoproject/layermap";
const DESCRIPTION =
  "A layered map of your codebase for coding agents: what calls a function, what a change affects up to the HTTP routes, handlers and jobs, and what each module contains, for TypeScript, JavaScript, Go, Python and Java. Built and kept locally; read-only.";
const KEYWORDS = [
  "code-map",
  "call-graph",
  "impact-analysis",
  "mcp",
  "typescript",
  "go",
  "python",
  "java",
];

export type ServerLaunch = Readonly<{
  command: string;
  args: readonly string[];
  env?: Record<string, string>;
}>;

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

/** Every file of both plugins and both marketplaces, by path relative to the repository root. */
export function pluginFiles(version: string, launch: ServerLaunch): Record<string, string> {
  const server = {
    command: launch.command,
    args: launch.args,
    ...(launch.env ? { env: launch.env } : {}),
  };
  const author = { name: "The LayerMap Authors", url: REPOSITORY };
  // Claude Code names a plugin's tools mcp__plugin_<plugin>_<server>__<tool>.
  const claudeTools = "mcp__plugin_layermap_layermap__.*";
  return {
    ".claude-plugin/marketplace.json": json({
      $schema: "https://anthropic.com/claude-code/marketplace.schema.json",
      name: "layermap",
      description: "LayerMap for Claude Code.",
      owner: author,
      plugins: [
        {
          name: "layermap",
          source: "./plugins/claude",
          description: DESCRIPTION,
          category: "development",
        },
      ],
    }),
    "plugins/claude/.claude-plugin/plugin.json": json({
      name: "layermap",
      displayName: "LayerMap",
      version,
      description: DESCRIPTION,
      author,
      homepage: REPOSITORY,
      repository: REPOSITORY,
      license: "Apache-2.0",
      keywords: KEYWORDS,
    }),
    "plugins/claude/.mcp.json": json({ mcpServers: { layermap: server } }),
    // The note an agent needs to reach for the map (natural-adoption runs), added at session start
    // instead of written into the user's CLAUDE.md; and the three read-only tools run unprompted.
    "plugins/claude/hooks/hooks.json": json({
      description:
        "Tells Claude when the map helps, and lets its read-only tools run without a prompt.",
      hooks: {
        SessionStart: [
          {
            hooks: [
              // biome-ignore lint/suspicious/noTemplateCurlyInString: Claude Code expands it when it runs the hook.
              { type: "command", command: 'node "${CLAUDE_PLUGIN_ROOT}/hooks/session-start.mjs"' },
            ],
          },
        ],
        PreToolUse: [
          {
            matcher: claudeTools,
            hooks: [
              {
                type: "command",
                // biome-ignore lint/suspicious/noTemplateCurlyInString: Claude Code expands it when it runs the hook.
                command: 'node "${CLAUDE_PLUGIN_ROOT}/hooks/allow-map-tools.mjs"',
              },
            ],
          },
        ],
      },
    }),
    "plugins/claude/hooks/session-start.mjs": `// Generated by scripts/plugins.ts.
process.stdout.write(
  JSON.stringify({
    hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: ${JSON.stringify(AGENT_MAP_NOTE)} },
  }),
);
`,
    "plugins/claude/hooks/allow-map-tools.mjs": `// Generated by scripts/plugins.ts. The map tools only read the project and its map.
process.stdout.write(
  JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      permissionDecisionReason: "LayerMap's tools only read the project and its map.",
    },
  }),
);
`,
    ".agents/plugins/marketplace.json": json({
      name: "layermap",
      interface: { displayName: "LayerMap" },
      plugins: [
        {
          name: "layermap",
          source: { source: "local", path: "./plugins/codex" },
          policy: { installation: "AVAILABLE", authentication: "ON_USE" },
          category: "Developer Tools",
        },
      ],
    }),
    "plugins/codex/.codex-plugin/plugin.json": json({
      name: "layermap",
      version,
      description: DESCRIPTION,
      author,
      homepage: REPOSITORY,
      repository: REPOSITORY,
      license: "Apache-2.0",
      keywords: KEYWORDS,
      skills: "./skills/",
      mcpServers: "./.mcp.json",
      interface: {
        displayName: "LayerMap",
        shortDescription:
          "Callers, callees and the impact of a change, from a local map of your code",
        longDescription: DESCRIPTION,
        developerName: "The LayerMap Authors",
        category: "Developer Tools",
        capabilities: ["Read"],
        websiteURL: REPOSITORY,
        defaultPrompt: [
          "What would changing this function affect? Trace its callers to the entry points.",
        ],
      },
    }),
    // Codex shows MCP tools only when it searches for them; a skill's description is always listed.
    "plugins/codex/.mcp.json": json({
      mcpServers: { layermap: { ...server, default_tools_approval_mode: "approve" } },
    }),
    "plugins/codex/skills/layermap/SKILL.md": `---
name: layermap
description: Use before grep or reading files when a task asks what calls a function or method, what changing it affects (up to HTTP routes, handlers, jobs and commands), where code is used, or how the code is organized. The layermap MCP tools answer these from a static map of the repository in one call.
---

# LayerMap

${AGENT_MAP_NOTE}

- \`project_explore_map\` with \`path\` "." shows what the repository contains; a file \`path\` lists its declarations; with \`name\` (and \`line\` when names repeat) it shows a declaration's callers and callees. \`direction\` INCOMING with \`depth\` up to 8 traces callers up to the entry points; continue from any NOT EXPANDED declarations it names.
- \`project_search_map\` finds a declaration by words in its name, path or documentation.
- \`project_find_references\` lists every usage of a declaration, compiled from current source.

The map is static: dynamic dispatch, framework wiring and unresolved targets need source reading, and a missing relationship does not prove absence. A large repository's first map takes minutes to build; until then the tools say so, and you can read source meanwhile.
`,
  };
}

async function main() {
  const version = JSON.parse(
    await readFile(path.join(packageRoot, "package.json"), "utf8"),
  ).version;
  const dev = process.argv.indexOf("--dev");
  const root = dev >= 0 ? path.resolve(process.argv[dev + 1] ?? "") : packageRoot;
  const launch: ServerLaunch =
    dev >= 0
      ? {
          command: process.execPath,
          args: [
            "--import",
            import.meta.resolve("tsx"),
            path.join(packageRoot, "src/cli.ts"),
            "mcp",
          ],
          ...(process.env.LAYERMAP_CACHE
            ? { env: { LAYERMAP_CACHE: process.env.LAYERMAP_CACHE } }
            : {}),
        }
      : { command: "npx", args: ["-y", `layermap@${version}`, "mcp"] };
  for (const [file, content] of Object.entries(pluginFiles(version, launch))) {
    await mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await writeFile(path.join(root, file), content);
  }
  process.stdout.write(`Plugins written under ${root}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]))
  await main();
